// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC_HRIS.Models;

public partial class EmployeePayslip
{
    public int EmployeeId { get; set; } // Employee ID
    public string EmployeeName { get; set; } // Employee Name
    public decimal GrossSalary { get; set; } // Gross Salary
    public decimal NetSalary { get; set; } // Net Salary
    public decimal TaxDeduction { get; set; } // Tax Deduction
    public decimal SSSDeduction { get; set; } // SSS Deduction
    public decimal PhilHealthDeduction { get; set; } // PhilHealth Deduction
    public decimal PagIbigDeduction { get; set; } // Pag-Ibig Deduction
    public DateTime PayDate { get; set; } // Pay Date
}