// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using X.PagedList;

namespace MVC_HRIS.Models;

public partial class PayslipViewModel
{
    public IPagedList<TblPayslipVM> Payslips { get; set; }
}