// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models
{
    public class EmployeeIdFilter
    {
        public string EmployeeNo { get; set; }
    }
}
