// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblDeductionModel
{
    [Key]
    public int Id { get; set; }
    [Required]
    [Column(TypeName = "varchar(100)")]
    [MaxLength(100)]
    public string DeductionName { get; set; } // SSS, PhilHealth, Pag-IBIG, Tax
    [Required, Column(TypeName = "decimal(18,2)")]
    public decimal Percentage { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal FixedAmount { get; set; }
    public int? Status { get; set; }
    public DateTime? DateCreated { get; set; } = DateTime.Now;
    public int? CreatedBy { get; set; }
    public bool? isDeleted { get; set; }
    public int? DeletedBy { get; set; }
    public DateTime? DateDeleted { get; set; }
}