// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace API_HRIS.Models;

public class TblHolidayModel
{
    [Key]
    public int Id { get; set; }

    [Required]
    [DataType(DataType.Date)]
    public DateTime Date { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    public bool IsRecurring { get; set; } // Optional: e.g. for yearly holidays like Christmas
}