// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblLeaveRequestModel
{
    public int Id { get; set; }
    public string? LeaveRequestNo { get; private set; }
    public string? EmployeeNo { get; set; }
    public string? ApprovalReason { get; set; }
    public DateTime? Date { get; set; }
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }
    public decimal? DaysFiled { get; set; }
    public int? LeaveTypeId { get; set; }
    public string? Reason { get; set; }
    public DateTime? DateCreated { get; set; }
    public int? Status { get; set; }
    public int? CreatedBy { get; set; }
    public bool? isDeleted { get; set; }
    public int? DeletedBy { get; set; }
    public DateTime? DateDeleted { get; set; }
    public int? UpdatedBy { get; set; }
    public DateTime? DateUpdated { get; set; }
}