// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblPayslipVM
{
    public string EmployeeName { get; set; }
    public string EmployeeNumber { get; set; }
    public string Department { get; set; }
    public string TaxNumber { get; set; }
    public string PayPeriod { get; set; }

    // Job Info
    public string PayslipNumber { get; set; }
    public string JobTitle { get; set; }
    public string EmploymentStatus { get; set; }
    public string SSSNumber { get; set; }
    public DateTime PayDate { get; set; }

    // Salary Details
    public decimal GrossPay { get; set; }
    public decimal NetPay { get; set; }

    // Deductions
    public decimal Tax { get; set; }
    public decimal SSS { get; set; }
    public decimal PhilHealth { get; set; }
    public decimal PagIbig { get; set; }
    public decimal OtherDeductions { get; set; }
    public decimal TotalDeductions { get; set; }
}