// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;

public partial class TblPayslipGeneratedDate
{
    public int Id { get; set; }

    public string P_GenID { get; set; }
    public DateTime? DateFrom { get; set; }
    public DateTime? DateTo { get; set; }
    public DateTime? DateCreated { get; set; }
    public string CreatedBy { get; set; }
    public int Status { get; set; }
}