// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblPayrollModel
{
    [Key]
    public int Id { get; set; }

    [Required, ForeignKey("Employee")]
    public int EmployeeId { get; set; }

    [Column(TypeName = "date")]
    public DateTime PayrollPeriod { get; set; }

    [Required, Column(TypeName = "decimal(18,2)")]
    public decimal GrossSalary { get; set; }

    [Required, Column(TypeName = "decimal(18,2)")]
    public decimal TotalDeductions { get; set; }

    [Required, Column(TypeName = "decimal(18,2)")]
    public decimal NetSalary { get; set; }
    [Required]
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string FilePath { get; set; }
    public int? Status { get; set; }
    public DateTime? DateCreated { get; set; } = DateTime.Now;
    public int? CreatedBy { get; set; }
    public bool? isDeleted { get; set; }
    public int? DeletedBy { get; set; }
    public DateTime? DateDeleted { get; set; }
}