// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblPayslipModel
{
    //mew
    [Key]
    public int PayslipId { get; set; }
    [Required]
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string EmployeeId { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal GrossSalary { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal SSSDeduction { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal PhilHealthDeduction { get; set; }
    public decimal PagIbigDeduction { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal TaxDeduction { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal NetSalary { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal RenderedHours { get; set; }
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string PayslipNumber { get; set; }
    public int? Status { get; set; }
    public DateTime? DateCreated { get; set; } = DateTime.Now;
    public int? CreatedBy { get; set; }
    public bool? isDeleted { get; set; }
    public int? DeletedBy { get; set; }
    public DateTime? DateDeleted { get; set; }
}