// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblPhilHealthModel
{
    [Key]
    public int Id { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal? Salary_From { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal? Salary_To { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal? Monthly_Premium { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal? Employer_Share { get; set; }
    [Column(TypeName = "decimal(18,2)")]
    public decimal? Employee_Share { get; set; }
    public int? Status { get; set; }
    public DateTime? DateCreated { get; set; } = DateTime.Now;
    public int? CreatedBy { get; set; }
    public bool? isDeleted { get; set; }
    public int? DeletedBy { get; set; }
    public DateTime? DateDeleted { get; set; }
}