// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace API_HRIS.Models;

public partial class TblPayrollPeriodModel
{
    [Key]
    public int Id { get; set; }
    [Required]
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string Name { get; set; }
    [Column(TypeName = "date")]
    public DateTime StartDate { get; set; }
    [Column(TypeName = "date")]
    public DateTime EndDate { get; set; }
    public bool IsClosed { get; set; }
    public int? Status { get; set; }
    public DateTime? DateCreated { get; set; } = DateTime.Now;
    public int? CreatedBy { get; set; }
    public bool? isDeleted { get; set; }
    public int? DeletedBy { get; set; }
    public DateTime? DateDeleted { get; set; }
}