// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;

public partial class TblScheduleDayModel
{
    public int Id { get; set; }
    public int? SchceduleId { get; set; }
    public int? Day { get; set; }
    public string? StartTime { get; set; }
    public string? EndTime { get; set; }
}