// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

    public partial class TblSSSModel
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Compensation_From { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Compensation_To { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Employer_RegularSS { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Employer_MPF { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Employer_EC { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Employer_Total { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Employee_RegularSS { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Employee_MPF { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Employee_Total { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal? Total_Contribution { get; set; }
        public int? Status { get; set; }
        public DateTime? DateCreated { get; set; } = DateTime.Now;
        public int? CreatedBy { get; set; }
        public bool? isDeleted { get; set; }
        public int? DeletedBy { get; set; }
        public DateTime? DateDeleted { get; set; }
    }